development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: melhor_ilhabela_development
  pool: 5
  username: root
  password: 1234
  host: localhost

staging:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: melhor_ilhabela_development
  pool: 5
  username: root
  password: 1234
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: melhor_ilhabela_test
  pool: 5
  username: root
  password: 1234
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: rs28066_melhorilhabela
  pool: 5
  username: rs28066_alberto
  password: yawali786
  host: bm10.webservidor.net

